/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {

    public static void main(String[] args) {

        Graph graph = new Graph();

        graph.addVertex("Anas");
        graph.addVertex("Ansam");
        graph.addVertex("Shahed");
        graph.addVertex("Khaith");

        graph.addEdge("Anas","Ansam");
        graph.addEdge("Anas", "Shahed");
        graph.addEdge("Anas", "Khaith");
        graph.addEdge("Ansam","Shahed");
        graph.addEdge("Shahed","Khaith");
        graph.addEdge("Khaith", "Ansam");

        System.out.println(graph.printGraph());


        System.out.println();
        System.out.println(graph.getVertices());

        System.out.println();
        System.out.println(graph.getNeighbors("Ansam"));

        System.out.println();
        System.out.println(graph.size());

    }

}

