/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        BinarySearchTree<Integer> binarySearchTree = new BinarySearchTree<Integer>();

        binarySearchTree.Add(2);
        binarySearchTree.Add(7);
        binarySearchTree.Add(5);
        binarySearchTree.Add(6);
        binarySearchTree.Add(11);
        binarySearchTree.Add(4);
        binarySearchTree.Add(9);
        
        BinarySearchTree<Integer> breadthTree = new BinarySearchTree();

        breadthTree.Add(20);
        breadthTree.Add(70);
        breadthTree.Add(40);
        breadthTree.Add(60);
        breadthTree.Add(50);


        System.out.println(binarySearchTree.FindMax());


        System.out.println("Inorder traversal of numbers " + binarySearchTree.inorderTraversal());

        System.out.println(" ");

        System.out.println("pre traversal of numbers " + binarySearchTree.preorderTraversal());

        System.out.println(" ");

        System.out.println("post traversal of numbers " +  binarySearchTree.postorderTraversal());

        System.out.println(binarySearchTree.Contains(5));

        // ********************************** Code Challenge 18 ******************************************

        KTree kTree = new KTree(1);

        kTree.add(1);
        kTree.add(5);
        kTree.add(20);
        kTree.add(21);
        kTree.add(6);
        kTree.add(15);

        System.out.println(kTree);
        System.out.println(kTree.fizzBuzzTree(kTree));


    }
}
