/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    public void addVertex(){

        Graph graph = new Graph();

        graph.addVertex("Anas");
        graph.addVertex("Ansam");

        assertNotNull(graph.getVertices());
        assertEquals(2,graph.size());
    }

    @Test
    public void addEdge(){

        Graph graph = new Graph();

        graph.addVertex("Anas");
        graph.addVertex("Shahid");
        graph.addEdge("Anas", "Shahid");

        assertEquals("Vertex{label='Shahid'}[Vertex{label='Anas'}]Vertex{label='Anas'}[Vertex{label='Shahid'}]", graph.printGraph());
    }

    @Test
    public void vertexNeighbors(){

        Graph graph = new Graph();

        graph.addVertex("Anas");
        graph.addVertex("Shahid");
        graph.addVertex("Khaith");
        graph.addVertex("Ansam");
        graph.addEdge("Anas", "Khaith");
        graph.addEdge("Anas", "Shahid");
        graph.addEdge("Ansam", "Shahid");

        assertEquals("[Vertex{label='Khaith'}, Vertex{label='Shahid'}]",graph.getNeighbors("Anas").toString());
        assertEquals("[Vertex{label='Shahid'}]", graph.getNeighbors("Ansam").toString());

    }

}
